### ISSUE TITLE
ansible playbook Enable acpid error - interactive auth required

### ISSUE THREAD

**Issue by robdew** [jmontleon/pixelbook-fedora#17]
Not sure why ```sudo systemctl enable acpid``` doesn't require interactive authentication but Ansible complains that the task does?

```sh
TASK [Enable acpid] ***********************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to enable service acpid: Failed to enable unit: Interactive authentication required.\n"}
```
5.14.10-300.fc35.x86_64

**Comment by dsem** [comment]
Are you running Ansible with the `-K` flag?

```
ansible-playbook -K playbook.yml
```

**Comment by robdew** [comment]
just checked my command history and I did run it w the -K flag.

**Comment by jmontleon** [comment]
I might have missed adding `become: true` here
https://github.com/jmontleon/pixelbook-fedora/blob/main/ansible/playbook.yml#L171

Would you mind editing the playbook, adding it, and seeing if that does the trick? If so I can PR it.

**Comment by robdew** [comment]
yep that fixed it.
```yaml
    - name: Enable acpid
      become: true
      systemd:
        name: acpid
        state: started
        enabled: yes
```
